First_Commit
abhicctech1003/OSGCADModeller pull request #2
Opened 2024-05-11 07:36 UTC by abhicctech1003

2024-05-12 12:37 UTC, vinayaksutar commented on OSGCADModeller/x64/Debug/OSGCADModeller.Build.CppClean.log
Remove log file

2024-05-12 12:38 UTC, vinayaksutar commented on OSGCADModeller/x64/Debug/OSGCADModeller.exe.recipe
Remove debug. Build files should be not on git

2024-05-12 12:39 UTC, vinayaksutar requested changes
1. Remove debug

2024-05-13 09:43 UTC, vinayaksutar requested changes
Remove auto generate and output files

2024-05-13 11:53 UTC, vinayaksutar approved these changes
For now approving but remove the auto generated files

2024-05-14 04:39 UTC, abhicctech1003 commented
> For now approving but remove the auto generated files

Thank you, will remove auto generated files in next PR

2024-05-14 04:39 UTC, merged